pipeline:
  build_docker_image:
    image: docker:19.03.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - PYTHON_VERSION=36
    commands:
      - docker build --build-arg PYTHON_VERSION --tag centos-python:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: centos-python:${DRONE_COMMIT_SHA}
    local_image: true
    when:
      event: push

  image_to_quay:
    image: docker:19.03.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - PYTHON_VERSION=36
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:$${DRONE_COMMIT_SHA}
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:$${PYTHON_VERSION}
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:latest
      - docker push quay.io/ukhomeofficedigital/centos-python:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/centos-python:$${PYTHON_VERSION}
      - docker push quay.io/ukhomeofficedigital/centos-python:latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: docker:19.03.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - PYTHON_VERSION=36
    commands:
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:$${DRONE_COMMIT_SHA}
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:$${PYTHON_VERSION}
      - docker tag centos-python:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-python:latest
      - docker push quay.io/ukhomeofficedigital/centos-python:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/centos-python:$${PYTHON_VERSION}
      - docker push quay.io/ukhomeofficedigital/centos-python:latest
    when:
      event: tag